### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by sebbmn** [HE-Arc-ODI/sp18-odi-serie2-odilee#2]
Je pense très honnêtement que ce code est truffé de bug. Prière de tout revoir, merci.

**Comment by odilee** [comment]
J ai entendu dire qu'il fallait se méfier des gens qui utilisent des ternaires

**Comment by sebbmn** [comment]
J'ai entendu dire que les gens qui copie colle des ternaires sont des malades.

**Comment by odilee** [comment]
oui ils finissent par faire des input stream...

**Comment by sebbmn** [comment]
Refactor svp

**Comment by sebbmn** [comment]
Je close cette issue, mais méfiez vous à l'avenir!
